### ISSUE TITLE
Creating new repositories in ASpace vs. failing?

### ISSUE THREAD

**Issue by noahgh221** [BitCurator/bc_to_aspace_toolkit#15]
Currently, the script creates new repository records in ASpace if there are no existing repositories that match the /test-repository directory name.

I think this could be potentially dangerous and would prefer that the script just fails (with an error message) if the /test-repository directory name in the Brunnhilde reports directory does not match an existing repository name in ASpace.

Of course, this would assume that a workflow would always involve creating an ASpace repository first, then running the script. Still, I'm imagining that you would almost always want to  import description into an existing ASpace repository rather than create a new one.

As background, at Duke we only manage two repositories in ASpace.

**Comment by kamwoods** [comment]
Agreed, I also had this concern. One alternative would be to allow it (for those who really want it) but make the user confirm several times with warning text. However, since the script only works on one repo at a time, but potentially many projects and datasets, eliminating repo creation entirely seems ok to me.

Side note - as far as I can tell ArchivesSpace doesn't seem provide any way to delete a repo in the interface. I assume this is for safety. I see that one of the devs published a script - years ago - that automates the process through the API (https://gist.github.com/cfitz/4fefcfa659ef18bfbe6c). I wonder if that still works?

**Comment by noahgh221** [comment]
If you're logged in as an administrator, I believe you can delete repositories in the staff interface.  Here is the API endpoint documentation: https://archivesspace.github.io/archivesspace/api/#delete-a-repository

**Comment by kamwoods** [comment]
Fixed in current master and v0.0.6 release. Script now warns and exits if repository_uri is not identified.
